name: Update Game Data

on:
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Debug directory structure
        run: |
          pwd
          ls -R

      - name: Create docs/data directory if it doesn't exist
        run: mkdir -p docs/data

      - name: Copy data files
        run: |
          cp -f data/merged_games.json docs/data/
          cp -f data/raw_games.json docs/data/

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add docs/data/*.json
          git commit -m "Update game data [skip ci]" || exit 0
          git push
