name: Update Game Data

on:
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Copy and commit changes
        run: |
          git config --global user.name 'Bastian Gruber'
          git config --global user.email 'foreach@me.com'
          git status
          git add docs/data/*.json
          git status
          git commit -m "Update game data [skip ci]"
          git log -1
          git push origin main --force
